### ISSUE TITLE
wrong license classifier

### ISSUE THREAD

**Issue by jonassmedegaard** [prrvchr/pyrdfa3#1]
The file `pyproject.toml` declares wrong classifier `License:: OSI Approved :: MIT`.
Correct classifier, corresponding with license statements in source files, is [License :: OSI Approved :: W3C License](https://pypi.org/search/?c=License+%3A%3A+OSI+Approved+%3A%3A+W3C+License).

**Comment by prrvchr** [comment]
Hi jonassmedegaard,

Having forgotten the notifications I only got your message today.

If you want to improve pyrdfa3 then send a PR I will integrate it into the new version that I will soon publish...

**Comment by prrvchr** [comment]
Done in [version 3.6.3](https://github.com/prrvchr/pyrdfa3/releases/tag/v3.6.3)
