### ISSUE TITLE
Deprecation of invalid escape chars: utils._unquotedChars

### ISSUE THREAD

**Issue by jayaddison** [prrvchr/pyrdfa3#4]
The following code began emitting a `SyntaxWarning` in Python 3.12, and should likely be updated to use a raw-string format as [described in the introductory section of the `re` docs](https://docs.python.org/3.12/library/re.html):

https://github.com/prrvchr/pyrdfa3/blob/dc9b5909553917fd4abf159238e704a4d6437266/src/pyRdfa/utils.py#L131

### Context / History
Python strings such as `'\w'` that contain invalid escape sequences have become frequently-used in regular expression code, because [regex syntax](https://docs.python.org/3.12/library/re.html#regular-expression-syntax) includes some character-classes that are indicated by a backslash followed by a single character.

The absence of any output warning/error when using standard Python string notation to represent those -- as opposed to a [raw string notation](https://docs.python.org/3.12/library/re.html#raw-string-notation)) -- has allowed these invalid-escape strings to appear organically in many codebases.

Python 3.6 [added a (silent-by-default) `DeprecationWarning`](https://github.com/python/cpython/issues/71551) for strings that contain invalid escape sequences, as part of an intention to gradually increase the severity the warning, and eventually for it to become a syntax error (rejected by the interpreter).  The deprecation warning occurs when the relevant Python warnings are enabled:

```pyi
# $ python -Walways
Python 3.11.8 (main, Feb  7 2024, 21:52:08) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> ':/\?=#~'
<stdin>:1: DeprecationWarning: invalid escape sequence '\?'
':/\\?=#~'
```

From Python 3.12 onwards, the [visibility of these syntax problems has been increased](https://github.com/python/cpython/issues/98401), and they begin emitting a `SyntaxWarning` message to the output by default:

```pyi
# $ python
Python 3.12.3 (main, Apr 10 2024, 03:39:08) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> ':/\?=#~'
<stdin>:1: SyntaxWarning: invalid escape sequence '\?'
':/\\?=#~'
```

A fix should be relatively straightforward and is essentially source-only; it affects the way that we represent the set of unquoted characters in the source code as written, and the runtime behaviour of the program (apart from warning/error output) should not change.

**Comment by jayaddison** [comment]
Ping @prrvchr - this relates to some syntax warnings emitted by Python3.12+ when using `pyrdfa3` - please also find a pull request linked to this one that I believe should resolve the problem.

**Comment by prrvchr** [comment]
Hi jayaddison,

Excuse me for never having seen your first message?

Thank you for participating in the maintenance of the pypdf3 package and  also for all these explanations concerning python 3.12 support.

I will integrate your PR into a new version. I don't have time today but I'll do it quickly.

**Comment by jayaddison** [comment]
Hi @prrvchr - a small reminder about these invalid escape character warnings (not urgent; just checking in case they might be forgotten).

**Comment by prrvchr** [comment]
> not urgent; just checking in case they might be forgotten

Thank you for reminding me, I will publish the new version tomorrow including your PR. Thanks.

**Comment by prrvchr** [comment]
Ok it's done with [version 3.6.4](https://github.com/prrvchr/pyrdfa3/releases/tag/v3.6.4). New requirements are needed. Thanks for your PR.

**Comment by jayaddison** [comment]
Thank you @prrvchr!
